# Generated by Django 5.2.8 on 2026-06-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('volcengine', '火山 Seedance'), ('aliyun', '阿里万相')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('prompt', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(default='1:1', max_length=16)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
                ('source_image', models.FileField(upload_to='uploads/')),
                ('remote_task_id', models.CharField(blank=True, max_length=255)),
                ('result_video', models.FileField(blank=True, upload_to='results/')),
                ('error_message', models.TextField(blank=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
